services:
  - type: web
    name: wgt-api
    env: node
    plan: free
    region: oregon
    buildCommand: "npm ci"
    startCommand: "node server.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_CHAT_MODEL
        value: gemini-2.0-flash
      - key: GEMINI_TTS_MODEL
        value: gemini-2.5-flash-preview-tts
      - key: GEMINI_TTS_VOICE
        value: Kore
    healthCheckPath: /api/healthz
